Modify initializer to check for valid paths at startup
bazelbuild/e4b pull request #18
Opened 2016-10-31 01:32 UTC by nanaze

2016-10-31 01:33 UTC, nanaze commented
fixes #17

2016-10-31 08:45 UTC, damienmg requested changes
Overall looks ok.

Ideally we would try to do a lookout on the path to find the bazel the user use, but this change is already a good improvement over the status quo.

2016-10-31 08:45 UTC, damienmg commented on CONTRIBUTORS
> +Nathan Naze <nanaze@gmail.com>
If you currently work at Google, please use your @google.com address

Add an empty line.

2016-10-31 08:45 UTC, damienmg commented on AUTHORS
> +Nathan Naze <nanaze@gmail.com>
If you are currently working at Google, remove your name, Google owns the copyright.

2016-10-31 08:45 UTC, damienmg commented on com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/preferences/BazelPreferenceInitializer.java
> +      if (new File(path).isFile()) {
Adds test for executable flag?

2016-10-31 08:45 UTC, damienmg commented on com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/preferences/BazelPreferenceInitializer.java
> +    System.err.println("No candidate path for blaze found. Using default.");
s/blaze/bazel

2016-10-31 08:45 UTC, damienmg commented on com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/preferences/BazelPreferenceInitializer.java
> +    System.err.println("No candidate path for blaze found. Using default.");
Do not use System.err.println, use Activator.error instead.

2016-10-31 08:45 UTC, damienmg commented on com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/preferences/BazelPreferenceInitializer.java
> +    System.err.println("No candidate path for blaze found. Using default.");
Also maybe tell in the message to go to the Eclipse preferences > Bazel to provide the path to Bazel.

2016-11-10 09:17 UTC, damienmg commented
@nanaze friendly ping

2017-02-13 12:33 UTC, damienmg commented
I have a concurrent change. Abandoning this one

2017-02-13 12:33 UTC, closed without merging